Library.Web/Models/ErrorViewModel.cs
namespace Library.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Library.Web/Controllers/AuthorsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Library.Common.Core;
using Library.Common.DTOs;
using Library.Web.Data.Entities;
using Library.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Library.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorsService _authorsService;
        private readonly INotyfService _notyfService;

        public AuthorsController(IAuthorsService authorsService, INotyfService notyfService)
        {
            _authorsService = authorsService;
            _notyfService = notyfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            Response<List<Author>> response = await _authorsService.GetListAsync();

            if (!response.IsSuccess)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(response.Result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }

            Response<Author> response = await _authorsService.CreateAsync(dto);
            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }

            _notyfService.Success(response.Message);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            Response<AuthorDTO> response = await _authorsService.GetOne(id);
            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return RedirectToAction("Index");
            }

            return View(response.Result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AuthorDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }
            Response<Author> response = await _authorsService.EditAsync(dto);
            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }
            _notyfService.Success(response.Message);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            Response<object> response = await _authorsService.DeleteAsync(id);
            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
            }
            else
            {
                _notyfService.Success(response.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

Library.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Library.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library.Web/Views/Authors/Create.cshtml
@model Library.Common.DTOs.AuthorDTO
@{
	ViewData["Title"] = "Nuevo Autor";
}

<h1>Nuevo Autor</h1>

<form asp-action="Create" method="POST">
	<div class="mb-3">
		<label for="FirstName" class="form-label">Nombres</label>
		<input asp-for="FirstName" type="text" class="form-control" id="FirstName" name="FirstName" placeholder="Digite los nombres...">
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label for="LastName" class="form-label">Apellidos</label>
		<input asp-for="LastName" type="text" class="form-control" id="LastName" name="LastName" placeholder="Digite los apellidos...">
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<button type="submit" class="btn btn-primary">Guardar</button>
	<a asp-action="Index" class="btn btn-secondary">Cancelar</a>

	@section Scripts 
	{
		@{
			await Html.RenderPartialAsync("_ValidationScriptsPartial");
		}
	}
</form>

Library.Web/Views/Authors/Edit.cshtml
@model Library.Common.DTOs.AuthorDTO
@{
	ViewData["Title"] = "Editar Autor";
}

<h1>Editar Autor</h1>

<form asp-action="Edit" method="POST">

	<input type="hidden" asp-for="Id" />

	<div class="mb-3">
		<label for="FirstName" class="form-label">Nombres</label>
		<input asp-for="FirstName" type="text" class="form-control" id="FirstName" name="FirstName" placeholder="Digite los nombres...">
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label for="LastName" class="form-label">Apellidos</label>
		<input asp-for="LastName" type="text" class="form-control" id="LastName" name="LastName" placeholder="Digite los apellidos...">
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<button type="submit" class="btn btn-warning">Guardar</button>
	<a asp-action="Index" class="btn btn-secondary">Cancelar</a>

	@section Scripts
 {
		@{
			await Html.RenderPartialAsync("_ValidationScriptsPartial");
		}
	}
</form>

Library.Web/Views/Authors/Index.cshtml
@model List<Author>

@{
	ViewData["Title"] = "Autores";
}

<h1>Autores</h1>

<a asp-action="Create" class="btn btn-primary">Nuevo Autor</a>

<table class="table table-bordered mt-3">

   <thead>
		<tr>
			<th>Nombres</th>
			<th>Apellidos</th>
			<th></th>
		</tr>
   </thead>
   <tbody>

		@foreach (Author author in Model)
		{
			<tr>
				<td>@author.FirstName</td>
				<td>@author.LastName</td>
				<td>
					<a asp-action="Edit" asp-route-id="@author.Id" class="btn btn-warning">Editar</a>
					<a asp-action="Delete" asp-route-id="@author.Id" class="btn btn-danger">Eliminar</a>
				</td>
			</tr>
		}

   </tbody>

</table>

Library.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Library.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Authors" asp-action="Index">Autores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Library.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>